# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

env:
  TERM: xterm-256color
  
font:
  normal:
    family: SF Mono 
    style: Regular 

  bold:
    family: SF Mono
    style: Bold

  italic:
    family: SF Mono
    style: Regular Italic

  bold_italic:
    family: SF Mono 
    style: Bold Italic

# VSCode's integrated terminal default colors
# Primary and dimmed colors needed
colors:
  # Default colors
  primary:
    background: '#1e1e1e' #Background from Dark Theme
    foreground: '#cccccc'

  # Selection colors
  selection:
    text: CellForeground
    background: '#565656'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#cd3131'
    green:   '#0dbc79'
    yellow:  '#e5e510'
    blue:    '#2472c8'
    magenta: '#bc3fbc'
    cyan:    '#11a8cd'
    white:   '#e5e5e5'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#f14c4c'
    green:   '#23d18b'
    yellow:  '#f5f543'
    blue:    '#3b8eea'
    magenta: '#d670d6'
    cyan:    '#29b8db'
    white:   '#e5e5e5'

